### ISSUE TITLE
Setting player modelling

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/Custom_DT#1]
## Description

* :star2: Goal: Being able to choose player settings without changing the code.
* :arrow_right: Making the difference at the dataset level (when loading and encoding the game)

## Acceptance Criterion

* [ ] The code is documented
* [x] Utilities and class test are written
* [x] The code was reviewed

## Tasks

* [x] Make a second dataset class
* [ ] Test game sequence in case of a loss or win
