### ISSUE TITLE
Play against AI

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/Custom_DT#15]
## Description

Being able to play against a trained model.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [ ] Write classes gameboard and player using `python-chess`
* [ ] Pay attention to illegal moves
* [ ] Write some tests about these classes
