### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/Custom_DT#19]
## Description

Add docstrings and possibly code examples.

## Acceptance Criterion

* [x] The code is documented
* [x] The code was reviewed

## Tasks

* [x] Standardise docstring for all classes and utilities
* [x] Add code examples if necessary
