### ISSUE TITLE
Implement Stockfish evals

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/Custom_DT#2]
## Description

* :star2: Goal: Being able to compute stockfish evals (and others) for a game.

## Acceptance Criterion

* [x] The code is documented
* [x] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [x] Implement stockfish evals in a `metric` module
* [x] Make the implementation a class similar to `sklearn` metrics
* [x] Add tests to ensure metric correctness
