### ISSUE TITLE
Make training easy

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/Custom_DT#20]
## Description

Simplify the training process.

## Acceptance Criterion

* [ ] The code is documented
* [x] Utilities and class tests are written
* [ ] The code was reviewed

## Tasks

* [x] Check modelling and add castling
* [x] Use args for training script
