### ISSUE TITLE
Lookahead attention

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/Custom_DT#4]
## Description

To be defined.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [ ] To be defined
