### ISSUE TITLE
[ARCHITECTURE] Register

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/Custom_DT#5]
## Description

* :star2: Goal: Implementing register tokens.
* :fire: Hot take: RTG tokens act as register tokens.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [ ] To be defined
